#include "Constants.h"

Vec2 GRAVITY = { 0.0f, -50.0f };
float RESTITUTION = 0.8f;
float AIR_RESISTANCE = 0.005f;
float INVERSE_AIR_RESISTANCE = 1.0f / AIR_RESISTANCE;
float MAX_VELOCITY = 200.0f;
float MAX_VELOCITY_SQ = MAX_VELOCITY * MAX_VELOCITY;
float MIN_DELTA_MOVEMENT = 0.005f; 
float DAMPING_FACTOR = 1.0f;
float SPACEBAR_FORCE_COEFFICIENT = 500.0f;
float LEFT_CLICK_FORCE_COEFFICIENT = 1000.0f;
float MAX_FORCE_DISTANCE_SQ = 50000.0f;
float THERMAL_DISPERSION_PER_FRAME = 0.1f;
float MAX_THERMAL_DIFFUSION_PER_COLLISION = 15.0f;

